path_chest_imagenome = "datasets/chest-imagenome-dataset"
path_mimic_cxr = "datasets/mimic-cxr"
path_mimic_cxr_jpg = "datasets/mimic-cxr-jpg"
path_full_dataset = "datasets/dataset-with-reference-reports"
# path_chexbert_weights = "/u/home/tanida/region-guided-chest-x-ray-report-generation/src/CheXbert/src/models/chexbert.pth"
# path_runs_object_detector = "/u/home/tanida/runs/object_detector"
# path_runs_full_model = "/u/home/tanida/runs/full_model"
# path_test_set_evaluation_scores_txt_files = "/u/home/tanida/region-guided-chest-x-ray-report-generation/src"
